// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5-Hb4JKRdMUzHHrXPSf4JxDhwCK6MeAY',
    appId: '1:918608137075:web:7964462b0975cb4e19d306',
    messagingSenderId: '918608137075',
    projectId: 'fir-example-7e0ae',
    authDomain: 'fir-example-7e0ae.firebaseapp.com',
    storageBucket: 'fir-example-7e0ae.appspot.com',
    measurementId: 'G-F3SRQ748SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY28LOhGS7YGwTCZnTgVz1bAN7gAR2nQA',
    appId: '1:918608137075:android:e0694eddb9fdfa6519d306',
    messagingSenderId: '918608137075',
    projectId: 'fir-example-7e0ae',
    storageBucket: 'fir-example-7e0ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKHq8Zk7mSuV-nJPFtd5H3qMFOeMfPr2I',
    appId: '1:918608137075:ios:924041d7e4085ac019d306',
    messagingSenderId: '918608137075',
    projectId: 'fir-example-7e0ae',
    storageBucket: 'fir-example-7e0ae.appspot.com',
    iosClientId: '918608137075-k4hte6rhktumrs58esn3jfha50nvr5tk.apps.googleusercontent.com',
    iosBundleId: 'com.learntogether.flutterFullCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKHq8Zk7mSuV-nJPFtd5H3qMFOeMfPr2I',
    appId: '1:918608137075:ios:924041d7e4085ac019d306',
    messagingSenderId: '918608137075',
    projectId: 'fir-example-7e0ae',
    storageBucket: 'fir-example-7e0ae.appspot.com',
    iosClientId: '918608137075-k4hte6rhktumrs58esn3jfha50nvr5tk.apps.googleusercontent.com',
    iosBundleId: 'com.learntogether.flutterFullCourse',
  );
}
